global:
  scrape_interval: 15s  # Fréquence de collecte des métriques

scrape_configs:
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node
    metrics_path: /metrics

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'  # Adresse de ton Alertmanager (si tu l'as configuré)
          
rule_files:
  - '/etc/prometheus/rules/alert.rules.yml'  # Fichier de règles d'alerte
